### PR TITLE
Remove Courses Page Feature

### LINKED ISSUE #6: REMOVE FEATURE: Remove unnecessary "Courses" page with poor user experience
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

user

### I can...

avoid being distracted by a poor user experience on the Courses page

### So that...

I can better work with personal schedules

### Discussion

There is currently a menu item in the courses app when logged in called "Courses" which lists the items in the table that stores entries for courses in a personal schedule:

image

When you click on `Courses` you get this:

image

However, this page is really of no value to the end user:
* The `Add New Course` button has been replaced by an `Add` button in the course search results.
* The `Delete` button will be added in another issue ( issue #89 in the proj-courses repo)
* The listing of courses is more useful on the Personal Schedule Details page

So it's time, once the delete button is added on the Personal Schedule Details page, to remove this page.

### Acceptance Criteria

- [ ] The page and route is no longer in `App.js`
- [ ] The page component, stories, and tests are removed, along with any other components (and their stories and tests) that were *only* used on that page.
- [ ] The menu item no longer appears

### Implementation Todos

Frontend:
- [x] Locate route in app.js
- [x] Trace through to find page components and other components to remove
- [x] Remove components, stories and tests
- [x] Remove item from navigation menu and adjust tests

### PR DESCRIPTION
**Pull request by tihdiR**
Merge Order:

1. #28  
2. #29 
3. This PR

Removed courses page files, CourseForm component, and relevant tests and stories. Adjusted Navbar and App.js accordingly.

Screen Shot 2024-05-27 at 4 53 28 PM

Closes #6

### CODE REVIEW

**Comment by pconrad** [comment]
Please note that this one should not be merged until 
https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-4/issues/2 is completed.

**Comment by pconrad** [comment]
Added PR-Stalled because this PR has sat in the queue for 4 days with no code review from the team.

**Review by andrew344c — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
